version: '3.8'

services:
###< doctrine/doctrine-bundle ###
    php:
        platform: linux/x86_64
        container_name: crune-php
        build:
            context: .
            args:
                CRUNE_VERSION: ${CRUNE_VERSION:-}
                SKELETON: ${SKELETON:-coral-media/crune}
                STABILITY: ${STABILITY:-stable}
                DEVELOPER_EMAIL: ${GIT_DEVELOPER_EMAIL:-developer@domain.com}
                DEVELOPER_USER: ${GIT_DEVELOPER_EMAIL:-developer}
            target: php
        ports:
            - '59000:9000'
        volumes:
            - ./:/srv/app:rw,cached
