services:
    php:
        platform: linux/amd64
        container_name: crune-php
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
            args:
                CRUNE_VERSION: ${CRUNE_VERSION:-}
                SKELETON: ${SKELETON:-coral-media/crune}
                STABILITY: ${STABILITY:-stable}
                DEVELOPER_EMAIL: ${GIT_DEVELOPER_EMAIL:-developer@domain.com}
                DEVELOPER_USER: ${GIT_DEVELOPER_EMAIL:-developer}
        ports:
            - '9000:9000'
        volumes:
            - ./:/srv/app:rw,cached
            - ./docker/php-fpm/.ssh:/root/.ssh:rw,cached
