services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $appName: '%app_name%'
            $appVersion: '%app_version%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Tests/'
            - '../src/Kernel.php'
